// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Spaceship_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Vector2 Flying;
        
        public Valve.VR.SteamVR_Action_Boolean Firing;
        
        public Valve.VR.SteamVR_Action_Boolean Pause;
        
        public Valve.VR.SteamVR_Action_Boolean Interact;
        
        public Valve.VR.SteamVR_Action_Boolean SwitchController;
        
        public Valve.VR.SteamVR_Action_Boolean UI_Interact;
    }
}
